delete from T_CONFIG where CFG_ID_C in ('LDAP_ENABLED', 'LDAP_HOST', 'LDAP_PORT', 'LDAP_USESSL', 'LDAP_ADMIN_DN', 'LDAP_ADMIN_PASSWORD', 'LDAP_BASE_DN', 'LDAP_FILTER', 'LDAP_DEFAULT_EMAIL', 'LDAP_DEFAULT_STORAGE');
update T_CONFIG set CFG_VALUE_C = '39' where CFG_ID_C = 'DB_VERSION';
