package com.sismics.docs.core.util;

import com.google.common.io.CharStreams;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

/**
 * Tests the document description sanitizer chokepoint.
 *
 * <p>Two complementary proofs: (1) every enabled Quill format's REAL serializer output
 * (checked-in fixtures generated by docs-web/scripts/export-quill-fixtures.mjs) survives
 * sanitization with its defining tag intact — so the allowlist can never drift below the
 * editor's capability; (2) hostile constructs (scripts, styles, iframes, event handlers,
 * javascript: URLs) are demonstrably stripped. The stripping assertions are
 * mutation-detecting: weakening {@link DescriptionSanitizer}'s allowlist (e.g. allowing
 * "script" or an event-handler attribute) makes the corresponding assertion fail.
 */
public class TestDescriptionSanitizer {

    private static String fixture(String name) throws Exception {
        try (InputStream is = TestDescriptionSanitizer.class.getResourceAsStream(
                "/description-fixtures/" + name + ".html")) {
            Assertions.assertNotNull(is, "missing fixture: " + name);
            return CharStreams.toString(new InputStreamReader(is, StandardCharsets.UTF_8)).trim();
        }
    }

    // --- fixture parity: each permitted construct survives sanitization ------------

    @Test
    public void headingFixtureSurvives() throws Exception {
        String out = DescriptionSanitizer.sanitize(fixture("heading"));
        Assertions.assertTrue(out.contains("<h1>") && out.contains("Heading"), out);
        Assertions.assertTrue(out.contains("<h2>") && out.contains("<h3>"), out);
    }

    @Test
    public void boldItalicUnderlineStrikeFixturesSurvive() throws Exception {
        Assertions.assertTrue(DescriptionSanitizer.sanitize(fixture("bold")).contains("<strong>"));
        Assertions.assertTrue(DescriptionSanitizer.sanitize(fixture("italic")).contains("<em>"));
        Assertions.assertTrue(DescriptionSanitizer.sanitize(fixture("underline")).contains("<u>"));
        Assertions.assertTrue(DescriptionSanitizer.sanitize(fixture("strike")).contains("<s>"));
    }

    @Test
    public void listFixturesSurvive() throws Exception {
        String ordered = DescriptionSanitizer.sanitize(fixture("list-ordered"));
        Assertions.assertTrue(ordered.contains("<ol>") && ordered.contains("<li>") && ordered.contains("first"), ordered);
        String bullet = DescriptionSanitizer.sanitize(fixture("list-bullet"));
        Assertions.assertTrue(bullet.contains("<ul>") && bullet.contains("<li>") && bullet.contains("alpha"), bullet);
    }

    @Test
    public void blockquoteFixtureSurvives() throws Exception {
        String out = DescriptionSanitizer.sanitize(fixture("blockquote"));
        Assertions.assertTrue(out.contains("<blockquote>") && out.contains("quoted"), out);
    }

    @Test
    public void codeBlockFixtureSurvives() throws Exception {
        String out = DescriptionSanitizer.sanitize(fixture("code-block"));
        Assertions.assertTrue(out.contains("<pre"), out);
        // The code text survives (the sanitizer defensively entity-encodes '=' as &#61;).
        Assertions.assertTrue(out.contains("const x") && out.contains("1;"), out);
        Assertions.assertTrue(out.contains("return x"), out);
        // The code content's own angle brackets stay entity-encoded (never live markup).
        Assertions.assertTrue(out.contains("&lt;") && out.contains("&gt;") && out.contains("&amp;"), out);
        // The narrowly-allowed data-language hint is preserved.
        Assertions.assertTrue(out.contains("data-language=\"plain\""), out);
    }

    @Test
    public void linkFixtureSurvivesWithSafeRelAndProtocol() throws Exception {
        String out = DescriptionSanitizer.sanitize(fixture("link"));
        Assertions.assertTrue(out.contains("href=\"https://teedy.example.com/path\""), out);
        Assertions.assertTrue(out.contains("Teedy"), out);
        // rel carries noopener + noreferrer (enforced by the policy, independent of input).
        Assertions.assertTrue(out.contains("noopener") && out.contains("noreferrer"), out);
    }

    @Test
    public void paragraphFixtureSurvives() throws Exception {
        String out = DescriptionSanitizer.sanitize(fixture("paragraph"));
        Assertions.assertTrue(out.contains("<p>") && out.contains("paragraph"), out);
    }

    // --- hostile input is stripped (mutation-detecting) ----------------------------

    @Test
    public void scriptElementIsStripped() {
        String out = DescriptionSanitizer.sanitize("<p>hi</p><script>alert(1)</script>");
        Assertions.assertFalse(out.contains("<script"), out);
        Assertions.assertFalse(out.contains("alert(1)"), out);
        Assertions.assertTrue(out.contains("<p>hi</p>"), out);
    }

    @Test
    public void styleElementAndAttributeAreStripped() {
        String out = DescriptionSanitizer.sanitize(
                "<style>body{display:none}</style><p style=\"color:red\">x</p>");
        Assertions.assertFalse(out.contains("<style"), out);
        Assertions.assertFalse(out.toLowerCase().contains("style="), out);
        Assertions.assertFalse(out.contains("display:none"), out);
    }

    @Test
    public void iframeIsStripped() {
        String out = DescriptionSanitizer.sanitize("<iframe src=\"https://evil.example\"></iframe><p>ok</p>");
        Assertions.assertFalse(out.toLowerCase().contains("<iframe"), out);
        Assertions.assertTrue(out.contains("<p>ok</p>"), out);
    }

    @Test
    public void eventHandlerAttributeIsStripped() {
        String out = DescriptionSanitizer.sanitize("<p onclick=\"alert(1)\">click</p>");
        Assertions.assertFalse(out.toLowerCase().contains("onclick"), out);
        Assertions.assertFalse(out.contains("alert(1)"), out);
        Assertions.assertTrue(out.contains("click"), out);
    }

    @Test
    public void imgWithOnerrorIsStripped() {
        String out = DescriptionSanitizer.sanitize("<img src=x onerror=\"alert(1)\">");
        Assertions.assertFalse(out.toLowerCase().contains("<img"), out);
        Assertions.assertFalse(out.toLowerCase().contains("onerror"), out);
        Assertions.assertFalse(out.contains("alert(1)"), out);
    }

    @Test
    public void javascriptUrlOnLinkIsStripped() {
        String out = DescriptionSanitizer.sanitize("<a href=\"javascript:alert(1)\">x</a>");
        Assertions.assertFalse(out.toLowerCase().contains("javascript:"), out);
        Assertions.assertFalse(out.contains("alert(1)"), out);
    }

    @Test
    public void dataUrlOnLinkIsStripped() {
        String out = DescriptionSanitizer.sanitize(
                "<a href=\"data:text/html,<script>alert(1)</script>\">x</a>");
        Assertions.assertFalse(out.toLowerCase().contains("data:text/html"), out);
        Assertions.assertFalse(out.toLowerCase().contains("<script"), out);
    }

    @Test
    public void protocolRelativeUrlOnLinkIsStripped() {
        // The pinned contract is http/https/mailto only. A protocol-relative //host URL is
        // an off-site navigation vector OWASP's default URL policy would otherwise allow —
        // the custom href policy drops it (the anchor text may remain, the href must not).
        String out = DescriptionSanitizer.sanitize("<a href=\"//evil.example/x\">go</a>");
        Assertions.assertFalse(out.contains("//evil.example"), out);
        Assertions.assertFalse(out.contains("href=\"//"), out);
        Assertions.assertTrue(out.contains("go"), out);
    }

    @Test
    public void leadingWhitespaceProtocolRelativeUrlIsStripped() {
        // A protocol-relative URL prefixed with control/whitespace must not slip past the
        // // check (the check trims the same leading control chars the URL policy ignores).
        String out = DescriptionSanitizer.sanitize("<a href=\"\t //evil.example/x\">go</a>");
        Assertions.assertFalse(out.contains("//evil.example"), out);
        Assertions.assertFalse(out.contains("href=\"//"), out);
    }

    @Test
    public void whitespaceObfuscatedJavascriptUrlIsStripped() {
        // Leading/embedded whitespace, tab, and newline forms of javascript: are all
        // neutralized (the library normalizes them; these lock the behavior).
        for (String href : new String[]{
                "\tjavascript:alert(1)",
                " javascript:alert(1)",
                "java\nscript:alert(1)",
                "java\tscript:alert(1)"}) {
            String out = DescriptionSanitizer.sanitize("<a href=\"" + href + "\">x</a>");
            Assertions.assertFalse(out.toLowerCase().contains("javascript:"), out);
            Assertions.assertFalse(out.contains("alert(1)"), out);
        }
    }

    @Test
    public void entityObfuscatedJavascriptUrlIsStripped() {
        // The HTML-entity form &#106;avascript: must not decode into a live javascript: href.
        String out = DescriptionSanitizer.sanitize("<a href=\"&#106;avascript:alert(1)\">x</a>");
        Assertions.assertFalse(out.toLowerCase().contains("javascript:"), out);
        Assertions.assertFalse(out.contains("alert(1)"), out);
    }

    @Test
    public void mailtoLinkIsAllowed() {
        // The mailto: scheme is permitted; the sanitizer defensively encodes '@' as &#64;.
        String out = DescriptionSanitizer.sanitize("<a href=\"mailto:user@example.com\">mail</a>");
        Assertions.assertTrue(out.contains("href=\"mailto:user"), out);
        Assertions.assertTrue(out.contains("example.com"), out);
    }

    @Test
    public void httpAndHttpsLinksSurvive() {
        // The fix must not over-restrict: absolute http/https hrefs still pass.
        String http = DescriptionSanitizer.sanitize("<a href=\"http://ok.example/a\">h</a>");
        Assertions.assertTrue(http.contains("href=\"http://ok.example/a\""), http);
        String https = DescriptionSanitizer.sanitize("<a href=\"https://ok.example/b\">s</a>");
        Assertions.assertTrue(https.contains("href=\"https://ok.example/b\""), https);
    }

    // --- composite XSS fixture (Quill-shaped payload) ------------------------------

    @Test
    public void xssQuillShapedPayloadStripped() throws Exception {
        String out = DescriptionSanitizer.sanitize(fixture("xss-quill-shaped"));
        Assertions.assertFalse(out.contains("<script"), out);
        Assertions.assertFalse(out.contains("</script"), out);
        Assertions.assertFalse(out.contains("onerror"), out);
        Assertions.assertFalse(out.contains("onclick"), out);
        Assertions.assertFalse(out.contains("javascript:"), out);
        Assertions.assertFalse(out.contains("data:"), out);
        Assertions.assertFalse(out.contains("style="), out);
        Assertions.assertFalse(out.contains("<iframe"), out);
        Assertions.assertFalse(out.contains("<img"), out);
        Assertions.assertFalse(out.contains("//evil.com"), out);
        Assertions.assertTrue(out.contains("<strong>"), out);
        Assertions.assertTrue(out.contains("<em>"), out);
        Assertions.assertTrue(out.contains("<blockquote>"), out);
        Assertions.assertTrue(out.contains("<pre"), out);
        Assertions.assertTrue(out.contains("<code>"), out);
        Assertions.assertTrue(out.contains("Normal paragraph text"), out);
        Assertions.assertTrue(out.contains("Legitimate bold stays"), out);
    }

    // --- contract behaviour --------------------------------------------------------

    @Test
    public void nullReturnsNull() {
        Assertions.assertNull(DescriptionSanitizer.sanitize(null));
    }

    @Test
    public void plainTextPassesThrough() {
        String out = DescriptionSanitizer.sanitize("just plain text, no markup");
        Assertions.assertEquals("just plain text, no markup", out);
    }

    @Test
    public void isIdempotent() throws Exception {
        // The DAO boundary re-applies the sanitizer over already-sanitized content, so a
        // second pass must not further mutate the result.
        for (String name : new String[]{"heading", "bold", "list-ordered", "link", "code-block", "blockquote"}) {
            String once = DescriptionSanitizer.sanitize(fixture(name));
            String twice = DescriptionSanitizer.sanitize(once);
            Assertions.assertEquals(once, twice, "sanitize must be idempotent for fixture " + name);
        }
    }
}
